# 2018-10-02-Promise研究

## 最近遇到一个xhr promise返回后执行相关操作的问题，因为对promise细节不太明了，所以作一些研究记录： 

1. 刚开始执行的是以下的代码，因为是分步执行的，执行到promiseResolve.then的时候并没有打印出'resolve',发现new Promise之后，Promise内部的代码会立即执行。


```javascript

var promiseResolve = new Promise((resolve, reject) => {
	setTimeout(resolve, 1000, 'resolve');
});
var promiseReject = new Promise((resolve, reject) => {
	setTimeout(resolve, 1000, 'reject');
});
promiseResolve.then(res=>console.log(res));
```

2. 于是换了一种写法：


```javascript
function getPromise(val){
	let ms = 1000;
	return new Promise((resolve, reject) => {
        val?setTimeout(resolve, ms, 'done'):setTimeout(reject, ms, 'error')
    });
}
getPromise(1)
    .then(res=>console.log(1),res=>console.log(2))
    .then(res=>console.log(3),res=>console.log(4))
// 2 3 

let sb = getPromise(1) ; sb.then(res=>console.log(1),res=>console.log(2));
sb.then(res=>console.log(3),res=>console.log(4))
// 2 4

```

3. 结论：开始用的是(return promise.then).then的写法，导致reject后第二个then依然会执行，所以需要在第一个then返回promise作处理，或者用更简单的方式：(promise.then return promise).then